(() => {
    const read=k=>{try{const v=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(v)?v:[]}catch{return[]}};
    const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
    let items=read("items"), rooms=read("rooms"), inventory=read("inventory");
    const canEdit=String(localStorage.getItem("role")||"").toUpperCase()==="STOREKEEPER";
    const formBox=document.getElementById("inventoryFormContainer"),form=document.getElementById("inventoryForm"),itemSel=document.getElementById("inventoryItem"),roomSel=document.getElementById("inventoryRoom"),qty=document.getElementById("sendQuantity"),sumBody=document.getElementById("inventorySummaryBody"),tableBody=document.getElementById("inventoryTableBody");
    if(!canEdit&&formBox)formBox.remove();
    const item=id=>items.find(x=>Number(x.id)===Number(id)); const room=id=>rooms.find(x=>Number(x.id)===Number(id));
    const total=id=>Number(item(id)?.quantity||0); const allocated=id=>inventory.filter(r=>Number(r.itemId)===Number(id)).reduce((s,r)=>s+Number(r.currentQuantity||0),0); const remaining=id=>Math.max(0,total(id)-allocated(id)); const nextId=a=>a.length?Math.max(...a.map(x=>Number(x.id)||0))+1:1;
    function load(){items=read("items");rooms=read("rooms");inventory=read("inventory");if(itemSel)itemSel.innerHTML='<option value="">Select Item</option>'+items.map(i=>`<option value="${i.id}">${i.name} - Remaining: ${remaining(i.id)}</option>`).join("");if(roomSel)roomSel.innerHTML='<option value="">Select Room</option>'+rooms.map(r=>`<option value="${r.id}">${r.name}</option>`).join("");}
    function display(){if(sumBody){sumBody.innerHTML=items.length?items.map(i=>`<tr><td><strong>${i.name}</strong></td><td>${total(i.id)}</td><td>${allocated(i.id)}</td><td><strong>${remaining(i.id)}</strong></td></tr>`).join(""):`<tr><td colspan="4" class="empty-state">No items registered yet</td></tr>`}if(tableBody){const valid=inventory.filter(r=>item(r.itemId)&&room(r.roomId));tableBody.innerHTML=valid.length?valid.map(r=>`<tr><td>${r.id}</td><td>${item(r.itemId).name}</td><td>${room(r.roomId).name}</td><td><strong>${Number(r.currentQuantity||0)}</strong></td><td>${canEdit?`<button class="btn btn-sm btn-primary" onclick="editAllocation(${r.id})">Edit</button> <button class="btn btn-sm btn-success" onclick="addQuantity(${r.id})">+ Add</button> <button class="btn btn-sm btn-warning" onclick="removeQuantity(${r.id})">- Remove</button> <button class="btn btn-sm btn-danger" onclick="deleteAllocation(${r.id})">Delete</button>`:`<span class="view-only">View Only</span>`}</td></tr>`).join(""):`<tr><td colspan="5" class="empty-state">No stock has been allocated yet</td></tr>`}}
    form?.addEventListener("submit",e=>{e.preventDefault();if(!canEdit)return;items=read("items");rooms=read("rooms");inventory=read("inventory");const iid=Number(itemSel.value),rid=Number(roomSel.value),n=Number(qty.value);if(!item(iid)||!room(rid))return alert("Please select a valid item and room.");if(!Number.isInteger(n)||n<=0)return alert("Quantity must be greater than zero.");if(n>remaining(iid))return alert(`Only ${remaining(iid)} unit(s) remaining for this item.`);const existing=inventory.find(r=>Number(r.itemId)===iid&&Number(r.roomId)===rid);if(existing){existing.currentQuantity=Number(existing.currentQuantity||0)+n}else{inventory.push({id:nextId(inventory),itemId:iid,roomId:rid,currentQuantity:n})}save("inventory",inventory);form.reset();load();display();alert(`Stock allocated successfully to ${room(rid).name}.`)});
    window.editAllocation=id=>{if(!canEdit)return;const r=inventory.find(x=>Number(x.id)===Number(id));if(!r)return;const max=total(r.itemId)-(allocated(r.itemId)-Number(r.currentQuantity||0));const n=Number(prompt("Enter quantity:",r.currentQuantity));if(!Number.isInteger(n)||n<=0)return alert("Invalid quantity.");if(n>max)return alert(`Maximum quantity allowed is ${max}.`);r.currentQuantity=n;save("inventory",inventory);load();display()};
    window.addQuantity=id=>{if(!canEdit)return;const r=inventory.find(x=>Number(x.id)===Number(id));if(!r)return;const max=remaining(r.itemId);const n=Number(prompt(`Enter quantity to add. Remaining stock: ${max}`));if(!Number.isInteger(n)||n<=0)return alert("Invalid quantity.");if(n>max)return alert(`Only ${max} unit(s) are remaining.`);r.currentQuantity=Number(r.currentQuantity||0)+n;save("inventory",inventory);load();display()};
    window.removeQuantity=id=>{if(!canEdit)return;const r=inventory.find(x=>Number(x.id)===Number(id));if(!r)return;const n=Number(prompt(`Enter quantity to remove. Current quantity: ${r.currentQuantity}`));if(!Number.isInteger(n)||n<=0)return alert("Invalid quantity.");if(n>Number(r.currentQuantity))return alert(`You cannot remove more than ${r.currentQuantity}.`);r.currentQuantity-=n;if(r.currentQuantity===0)inventory=inventory.filter(x=>Number(x.id)!==Number(id));save("inventory",inventory);load();display()};
    window.deleteAllocation=id=>{if(!canEdit)return;if(!confirm("Delete this allocation? The stock will return to Remaining Stock."))return;inventory=inventory.filter(x=>Number(x.id)!==Number(id));save("inventory",inventory);load();display()};
    load();display();
})();
